# ryEx001


In [1]:
1

1

In [2]:
1.2

1.2

$
\vec{1}
$


# Introduction to Linear Algebra with NumPy

- https://numpy.org/doc/stable/user/tutorial-svd.html


- https://towardsdatascience.com/introduction-to-linear-algebra-with-numpy-79adeb7bc060


In [3]:
import numpy as np


In [6]:
v= [1, 2, 3, 4]
v

[1, 2, 3, 4]

In [9]:
v= np.array(v)
v

array([1, 2, 3, 4])

In [10]:
v.shape

(4,)

In [11]:
A= [[1,2,3,4],
    [5,6,7,8]]
A

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [12]:
A= np.array(A)
A

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
A.shape

(2, 4)

In [14]:
T=[[1,2,3,4],
   [5,6,7,8],
   [9,10,11,12],
   [13,14,15,16]]
T

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]

In [15]:
T= np.array(T)
T

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [16]:
T.shape

(4, 4)

In [18]:
T= T.reshape((2,2,4))
T

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [19]:
T.shape

(2, 2, 4)

In [20]:
T[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
T[1]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [22]:
v.ndim

1

In [23]:
A.ndim

2

In [24]:
T.ndim

3

![](https://miro.medium.com/max/555/0*Vh-pKXTJsdL-9FT0.png)

In [27]:
T4d= T.reshape(2,2,2,2)
T4d

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [28]:
T4d.shape

(2, 2, 2, 2)

In [31]:
v, A, T, T4d

(array([1, 2, 3, 4]),
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],
 
        [[ 9, 10, 11, 12],
         [13, 14, 15, 16]]]),
 array([[[[ 1,  2],
          [ 3,  4]],
 
         [[ 5,  6],
          [ 7,  8]]],
 
 
        [[[ 9, 10],
          [11, 12]],
 
         [[13, 14],
          [15, 16]]]]))

In [32]:
v

array([1, 2, 3, 4])

In [35]:
v14= v.reshape(1,4)
v14

array([[1, 2, 3, 4]])

In [36]:
v41= v.reshape(4,1)
v41

array([[1],
       [2],
       [3],
       [4]])

In [37]:
v.shape, v14.shape, v41.shape

((4,), (1, 4), (4, 1))

# Vector Operations

We have covered the basic structures. Now it is time to discuss basic operations that can be done on these structures.
