# ryEx001.ipynb
- 嚐一下 矩陣及向量的運算


In [174]:
import numpy as np

# Vector Operations

We have covered the basic structures. Now it is time to discuss basic operations that can be done on these structures.


In [175]:
A= [[1,2,3],
    [4,5,6],
    [7,8,9]]
A= np.array(A)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [176]:
# row vector, 1-D array
r0= A[0,:]
r1= A[1,:]
r2= A[2,:]
r0,r1,r2

(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

In [177]:
# column vector, 1-D array
c0= A[:,0]
c1= A[:,1]
c2= A[:,2]
c0,c1,c2


(array([1, 4, 7]), array([2, 5, 8]), array([3, 6, 9]))

In [178]:
# reshape the row-, column- vector
r0= r0.reshape(1,-1)
r1= r1.reshape(1,-1)
r2= r2.reshape(1,-1)

c0= c0.reshape(-1,1)
c1= c1.reshape(-1,1)
c2= c2.reshape(-1,1)



In [179]:
r0

array([[1, 2, 3]])

In [180]:
c0

array([[1],
       [4],
       [7]])

In [181]:
A*r0, r0*A

(array([[ 1,  4,  9],
        [ 4, 10, 18],
        [ 7, 16, 27]]),
 array([[ 1,  4,  9],
        [ 4, 10, 18],
        [ 7, 16, 27]]))

In [182]:
A*c0, c0*A

(array([[ 1,  2,  3],
        [16, 20, 24],
        [49, 56, 63]]),
 array([[ 1,  2,  3],
        [16, 20, 24],
        [49, 56, 63]]))

In [184]:
A@r0

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)

In [185]:
r0@A

array([[30, 36, 42]])

In [186]:
A@c0

array([[ 30],
       [ 66],
       [102]])

In [187]:
c0@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 1)

In [188]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [189]:
import scipy.linalg as sl



In [190]:
p,l,u= sl.lu(A)

In [191]:
p@l@u

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [192]:
p

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [193]:
sl.inv(A)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [194]:
A= np.array([[1,2,3],[4,5,6],[7,9,8]])

In [195]:
p,l,u= sl.lu(A)

In [196]:
p@l@u

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 9., 8.]])

In [197]:
sl.svd?

Signature:
sl.svd(
    a,
    full_matrices=True,
    compute_uv=True,
    overwrite_a=False,
    check_finite=True,
    lapack_driver='gesdd',
)
Docstring:
Singular Value Decomposition.

Factorizes the matrix `a` into two unitary matrices ``U`` and ``Vh``, and
a 1-D array ``s`` of singular values (real, non-negative) such that
``a == U @ S @ Vh``, where ``S`` is a suitably shaped matrix of zeros with
main diagonal ``s``.

Parameters
----------
a : (M, N) array_like
    Matrix to decompose.
full_matrices : bool, optional
    If True (default), `U` and `Vh` are of shape ``(M, M)``, ``(N, N)``.
    If False, the shapes are ``(M, K)`` and ``(K, N)``, where
    ``K = min(M, N)``.
compute_uv : bool, optional
    Whether to compute also ``U`` and ``Vh`` in addition to ``s``.
    Default is True.
overwrite_a : bool, optional
    Whether to overwrite `a`; may improve performance.
    Default is False.
check_finite : bool, optional
    Whether to check that the input matrix contains only finite

In [198]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [199]:
u,s,v= np.linalg.svd(A)

In [200]:
u@np.diag(s)@v

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 9., 8.]])

In [201]:
u

array([[-0.21282399,  0.71583522,  0.66504577],
       [-0.51989242,  0.49333029, -0.69737873],
       [-0.82729548, -0.49417118,  0.26716479]])

In [202]:
u[:,0]@u[:,1]

-5.551115123125783e-17

In [203]:
v[:,0]@v[:,0]

1.0

In [204]:
A=np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [205]:
np.linalg.svd(A)

(array([[-0.40455358, -0.9145143 ],
        [-0.9145143 ,  0.40455358]]),
 array([5.4649857 , 0.36596619]),
 array([[-0.57604844, -0.81741556],
        [ 0.81741556, -0.57604844]]))

# 計算行列式 
- recursive formula
- 超級漂亮
- https://en.wikipedia.org/wiki/Laplace_expansion
![](https://wikimedia.org/api/rest_v1/media/math/render/svg/5ed201576483cebc15b497f91951651715e37847)
- 拜讀！！

In [206]:
def determinant(M):
    # Base case of recursive function: 1x1 matrix
    if len(M) == 1: 
        return M[0][0]

    total = 0
    for column, element in enumerate(M[0]):
        # Exclude first row and current column.
        K = [x[:column] + x[column + 1 :] for x in M[1:]]
        s = 1 if column % 2 == 0 else -1 
        total += s * element * determinant(K)
    return total

In [207]:
M= [[ 1, -2,  3,   4],
    [ 5,  6, -7,   8],
    [ 9, 10, 11, -12],
    [13, 14, 15,  16]]

determinant(M)

11232

In [208]:
# 與 numpy.linalg.det() 比較，作為驗證！
np.linalg.det(M)

11232.0

# Gaussian Elimination
# LU decomposition
