# ryEx001.ipynb
- 嚐一下 矩陣及向量的運算


In [2]:
import numpy as np

# Vector Operations

We have covered the basic structures. Now it is time to discuss basic operations that can be done on these structures.


In [3]:
A= [[1,2,3],
    [4,5,6],
    [7,8,9]]
A= np.array(A)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# row vector, 1-D array
r0= A[0,:]
r1= A[1,:]
r2= A[2,:]
r0,r1,r2

(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

In [5]:
# column vector, 1-D array
c0= A[:,0]
c1= A[:,1]
c2= A[:,2]
c0,c1,c2


(array([1, 4, 7]), array([2, 5, 8]), array([3, 6, 9]))

In [6]:
# reshape the row-, column- vector
r0= r0.reshape(1,-1)
r1= r1.reshape(1,-1)
r2= r2.reshape(1,-1)

c0= c0.reshape(-1,1)
c1= c1.reshape(-1,1)
c2= c2.reshape(-1,1)



In [7]:
r0

array([[1, 2, 3]])

In [8]:
c0

array([[1],
       [4],
       [7]])

In [9]:
A*r0, r0*A

(array([[ 1,  4,  9],
        [ 4, 10, 18],
        [ 7, 16, 27]]),
 array([[ 1,  4,  9],
        [ 4, 10, 18],
        [ 7, 16, 27]]))

In [10]:
A*c0, c0*A

(array([[ 1,  2,  3],
        [16, 20, 24],
        [49, 56, 63]]),
 array([[ 1,  2,  3],
        [16, 20, 24],
        [49, 56, 63]]))

In [11]:
A@r0

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)

In [ ]:
r0@A

In [ ]:
A@c0

In [ ]:
c0@A

In [ ]:
A

In [ ]:
import scipy.linalg as sl



In [ ]:
p,l,u= sl.lu(A)

In [ ]:
p@l@u

In [ ]:
p

In [ ]:
sl.inv(A)

In [ ]:
A= np.array([[1,2,3],[4,5,6],[7,9,8]])

In [ ]:
p,l,u= sl.lu(A)

In [ ]:
p@l@u

In [ ]:
sl.svd?

In [ ]:
np.diag([1,2,3])

In [ ]:
u,s,v= np.linalg.svd(A)

In [ ]:
u@np.diag(s)@v

In [ ]:
u

In [ ]:
u[:,0]@u[:,1]

In [ ]:
v[:,0]@v[:,0]

In [ ]:
A=np.array([[1,2],[3,4]])
A

In [ ]:
np.linalg.svd(A)

# 計算行列式 
- recursive formula
- 超級漂亮
- https://en.wikipedia.org/wiki/Laplace_expansion
![](https://wikimedia.org/api/rest_v1/media/math/render/svg/5ed201576483cebc15b497f91951651715e37847)
- 拜讀！！

In [ ]:
def determinant(M):
    # Base case of recursive function: 1x1 matrix
    if len(M) == 1: 
        return M[0][0]

    total = 0
    for column, element in enumerate(M[0]):
        # Exclude first row and current column.
        K = [x[:column] + x[column + 1 :] for x in M[1:]]
        s = 1 if column % 2 == 0 else -1 
        total += s * element * determinant(K)
    return total

In [ ]:
M= [[ 1, -2,  3,   4],
    [ 5,  6, -7,   8],
    [ 9, 10, 11, -12],
    [13, 14, 15,  16]]

determinant(M)

In [ ]:
# 與 numpy.linalg.det() 比較，作為驗證！
np.linalg.det(M)

# Gaussian Elimination
# LU decomposition
