# HomeWork 示範：


## Exercises

1. Compute the LU decomposition of the following matrix by hand and using numpy

A= [[1,  2,  3],
    [2, -4,  6],
    [3, -9, -3]]

- 運用 TeX 語法，使數學符號更漂亮一點：

$
A=
\left[
\begin{matrix} 
1 &  2 & 3   \\
2 & -4 & 6   \\
3 & -9 & -3
\end{matrix}
\right]
$


In [11]:
import numpy as np
import scipy.linalg as sp_linalg


In [2]:
A= [[1,  2,  3],
    [2, -4,  6],
    [3, -9, -3]]
A= np.array(A)
A

array([[ 1,  2,  3],
       [ 2, -4,  6],
       [ 3, -9, -3]])

In [4]:
P,L,U= sp_linalg.lu(A)
P, L, U

(array([[0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]]),
 array([[1.        , 0.        , 0.        ],
        [0.33333333, 1.        , 0.        ],
        [0.66666667, 0.4       , 1.        ]]),
 array([[ 3. , -9. , -3. ],
        [ 0. ,  5. ,  4. ],
        [ 0. ,  0. ,  6.4]]))

In [5]:
# 驗算
P@L@U

array([[ 1.,  2.,  3.],
       [ 2., -4.,  6.],
       [ 3., -9., -3.]])

In [9]:
assert (A==P@L@U).all()

In [8]:
assert np.allclose(A, P@L@U)