In [2]:
import numpy as np
import matplotlib.pyplot as plt

# pdensities of x, x^2, and x^3
%matplotlib qt
t= np.linspace(-10,10,1000)
fig, ax= plt.subplots(2,5)
fig.set_size_inches(12,6) # width, height in inches
for i in range(5):
    #i=1    
    # histogram of the function
    values= t**i
    
    #np.random.shuffle(values) # 加上這行頗為有趣
    
    counts, value_bins= np.histogram(values, 30)
    counts= counts #/ sum(counts)
    
    # plot the function
    ax[0,i].plot(values, t)
    ax[0,i].set_xlabel('values')
    ax[0,i].set_ylabel('t')
    ax[0,i].set_title(f'$values= t^{i}$')
    
    # plot its distribution
    ax[1,i].stem(
        value_bins[:-1],
        counts)
    ax[1,i].set_xlabel('value_bins')
    ax[1,i].set_ylabel('counts')
    
    
plt.show()


In [3]:
# 3 個 在時間軸上 不同的訊號，
# 使用 np.histogram() 把它們視為相同的機率分布！
t= np.linspace(-10,10,1001)
#t= np.arange(-10,10)
X= np.sin(t*2) #t**2
X1= np.sort(X)
X2= X.copy()
np.random.shuffle(X2)  # 這個 .shuffle() 每次結果都不同！！
f, x= np.histogram(X, bins=20)
f= np.insert(f,0,0)  
# 上面這一行是 ry 特殊補丁，
# .histogram() 做出的 f, x 長度不同，影響後面程式碼的簡潔！
f1, x1= np.histogram(X1, bins=20)
f1= np.insert(f1,0,0)  
f2, x2= np.histogram(X2, bins=20)
f2= np.insert(f2,0,0)
t, X, X1, X2
x, f, x1, f1, x2, f2


(array([-0.99999923, -0.89999931, -0.79999938, -0.69999946, -0.59999954,
        -0.49999962, -0.39999969, -0.29999977, -0.19999985, -0.09999992,
         0.        ,  0.09999992,  0.19999985,  0.29999977,  0.39999969,
         0.49999962,  0.59999954,  0.69999946,  0.79999938,  0.89999931,
         0.99999923]),
 array([  0, 137,  62,  49,  43,  39,  37,  35,  33,  33,  32,  33,  33,
         33,  35,  37,  39,  43,  49,  62, 137], dtype=int64),
 array([-0.99999923, -0.89999931, -0.79999938, -0.69999946, -0.59999954,
        -0.49999962, -0.39999969, -0.29999977, -0.19999985, -0.09999992,
         0.        ,  0.09999992,  0.19999985,  0.29999977,  0.39999969,
         0.49999962,  0.59999954,  0.69999946,  0.79999938,  0.89999931,
         0.99999923]),
 array([  0, 137,  62,  49,  43,  39,  37,  35,  33,  33,  32,  33,  33,
         33,  35,  37,  39,  43,  49,  62, 137], dtype=int64),
 array([-0.99999923, -0.89999931, -0.79999938, -0.69999946, -0.59999954,
        -0.49999962, -0.3

In [5]:
import matplotlib.pyplot as pl

fg1= pl.figure('fg1')
ax1= pl.axes()
ax1.plot(t,X,'ro',t,X1,'gx',t,X2,'b.')
ax1.set_xlabel('t')
ax1.set_ylabel('X, X1, X2')
ax1.legend(['X','X1','X2'])
fg2= pl.figure('fg2')
ax2= pl.axes()
ax2.plot(f,x,'ro',f1,x1,'gx',f2,x2,'b.')
ax2.plot(f,x,'r-',f1,x1,'g--',f2,x2,'b-.')
ax2.set_xlabel('f, f1, f2')
ax2.set_ylabel('x')
ax2.legend(['f','f1','f2'])
fg3= pl.figure('fg3')
ax3= pl.axes()
ax3.plot(x,f,'ro',x1,f1,'gx',x2,f2,'b.')
ax3.plot(x,f,'r-',x1,f1,'g--',x2,f2,'b-.')
ax3.set_ylabel('f, f1, f2')
ax3.set_xlabel('x')
ax3.legend(['f','f1','f2'])


In [6]:
# 封裝測試一下...，允許輸入不同函數
# 加碼練習 subplot()
# 加碼觀察 cumsum()
def ryHistogram_demo(func= None):
    
    # 在時間軸上 不同的訊號，
    # 使用 np.histogram() 把它們視為相同的機率分布！
    t= np.linspace(-10,10,1001)
    #t= np.arange(-10,10)
    
    if func==None:
        func= np.sin
        
    X= func(t) #t**2
    
    X1= np.sort(X)
    X2= X.copy()
    np.random.shuffle(X2)  # 這個 .shuffle() 每次結果都不同！！
    f, x= np.histogram(X, bins=20)
    f= np.insert(f,0,0)  
    # 上面這一行是 ry 特殊補丁，
    # .histogram() 做出的 f, x 長度不同，影響後面程式碼的簡潔！
    f1, x1= np.histogram(X1, bins=20)
    f1= np.insert(f1,0,0)  
    f2, x2= np.histogram(X2, bins=20)
    f2= np.insert(f2,0,0)
    t, X, X1, X2
    x, f, x1, f1, x2, f2
    
    # 加碼觀察 cumsum
    F= np.cumsum(f)
    
    #fg1= pl.figure('fg1')
    #ax= pl.axes()
    
    fg, ax = plt.subplots(2,2,figsize=(10,5))
    
    ax[0,0].plot(t,X,'ro',t,X1,'gx',t,X2,'b.')
    ax[0,0].set_xlabel('t')
    ax[0,0].set_ylabel('X, X1, X2')
    ax[0,0].legend(['X','X1','X2'])
    
    #'''
    #fg2= pl.figure('fg2')
    #ax2= pl.axes()
    ax[0,1].plot(f,x,'ro--',f1,x1,'gx-.',f2,x2,'b.-',F,x,'cs--')
    ax[0,1].set_xlabel('f, f1, f2, F')
    ax[0,1].set_ylabel('x')
    ax[0,1].legend(['f','f1','f2','F'])
    #'''
    #fg3= pl.figure('fg3')
    #ax3= pl.axes()
    ax[1,0].plot(x,f,'ro--',x1,f1,'gx-',x2,f2,'b.-', x,F,'cs--')
    ax[1,0].set_ylabel('f, f1, f2, F')
    ax[1,0].set_xlabel('x')
    ax[1,0].legend(['f','f1','f2','F'])
    
    # 加碼觀察 cumsum
    # 本想簡單達成
    # 但 加 legend() 出問題，只好把以下幾行混進上面程式碼中，殘念！！！
    
    '''
    F= np.cumsum(f)
    
    ax[1,0].plot(x,F,'cs-')
    #ax[1,0].legend(['F'])
    
    ax[0,1].plot(F,x,'cs-')
    #ax[0,1].legend(['F'])
    '''
    
ryHistogram_demo()


In [7]:
def f(t):
    y= np.sin(t)
    #y= t**2
    #y= np.sin(t) + np.sin(t*2) + np.sin(t*3)
    #y= (t+10) * (t+5)* (t)* (t-4) * (t-9)
    
    return y
ryHistogram_demo(f)


In [11]:
#
# 這圖超有梗: 
# 可以再說明一下...
#
# sort(), shuffle(), histogram(), cumsum(), diff(), modf()
#
#
t= np.linspace(0,10,100)
x= t.copy()
y= abs(np.modf(x/10)[0]-.5)*2  #有梗
#y= y**2  #可以變化試試看
y1= y.copy()
y1= np.sort(y1) #有梗
y2= y.copy()
np.random.shuffle(y2) #有梗
ax= pl.axes()
ax.clear()
ax.plot(x, y,  'ro-')
ax.plot(x, y1, 'g^--')
ax.plot(x, y2, 'bs--')
f, x1= np.histogram(y) #有梗
x1= x1[:-1]            #有小梗
ax.barh(x1, width=f/10, 
        height=.06, color='magenta', alpha= .5, align='edge')
F= f.cumsum()  #有梗
ax.barh(x1, width=F/10, 
        height=.08, color='gray', alpha= .5, align='edge')
dF= np.diff(F) #有梗
dF= np.insert(dF,0,F[0]) # 這裡也有小小的梗
ax.barh(x1, width= dF/10, 
        height=.02, color='purple', alpha= .5, align='edge')
ax.set_title('y= y(t), f= f(y), F= F(y), dF= dF(y)')
ax.set_xlabel('t, f, F')
ax.set_ylabel('y')
ax.legend(['y= y(t)','y1= sort(y)','y2= shuffle(y)',
           'f= histogram(y)','F= cumsum(f)', 'dF= diff(F)'])


In [12]:
# 中央極限定理 Central Limit Theorem
#
# generate data from various distributions, then sum them
# the sum will approach a normal distribution
#
sampleSize= 1000
t= np.arange(sampleSize)  
# 加總 100 個 隨機變數，陽春Python經典作法
X= 0 
for i in range(100):
    X += np.random.random(size= sampleSize)
# 加總 100 個 隨機變數， Python 經典做法 之2: list comprehension 
X100= [np.random.random(sampleSize)  for i in range(100)]
X=    sum(X100)
# 加總 100 個 隨機變數， numpy 經典做法，要注意 shape，axis
X100= np.random.random((100, sampleSize)) # .shape= (100, sampleSize)
X=    X100.sum(axis=0) # .shape= (1, sampleSize) ==> 再進化為 (sampleSize, )
f, x= np.histogram(X)
x= x[:-1]
fg, ax= pl.subplots(1,2)
for i in range(0,100,2):
    ax[0].plot(t, X100[i], alpha= .1)
ax[0].plot(t,X)
ax[1].plot(f,x)
ax[0].set_xlabel('t')
ax[0].set_ylabel('X')
ax[0].set_title('sum 100 independent random variables')
ax[1].set_xlabel('f')
ax[1].set_ylabel('x')
ax[1].set_title(' the sum of them will approach a Normal distribution')
ax[0].set_ylim([0,100])
ax[1].set_ylim([0,100])


(0.0, 100.0)

In [13]:
import numpy  as np
import pandas as pd
%matplotlib qt
pl.rcParams['axes.prop_cycle']= pl.cycler(
    color=['red', 
           'orange', 
           'yellow', 
           'green',
           'cyan',
           'blue',
           'purple',
           'magenta',
           'gray',
           'black'])
    
    
def ryUniformVsNormal(sampSize= 1000):
    
    X= pd.DataFrame(np.zeros((sampSize, 1)))
    for i in range(0,8):
        a= i-1/2
        b= i+1/2
        X[i]= np.random.uniform(
                low=  a, 
                high= b,
                size= sampSize)
    
    #X= X.cumsum()
    X.plot(title= 'uniform', alpha= .5)
    X.hist()
    
    
    Y= pd.DataFrame(np.zeros((sampSize, 1)))
    for i in range(0,8):
        μ= i
        σ= 1/2
        Y[i]= np.random.normal( 
                loc=   μ,  
                scale= σ,
                size= sampSize)
    #Y=Y.cumsum()
    Y.plot(alpha= .5, title= 'normal')
    Y.hist()
    
ryUniformVsNormal(sampSize= 1000)


In [14]:
import numpy  as np
import pandas as pd  # 偷用一下…
%matplotlib qt
pl.rcParams['axes.prop_cycle']= pl.cycler(
    color=['red', 
           'orange', 
           'yellow', 
           'green',
           'cyan',
           'blue',
           'purple',
           'magenta',
           'gray',
           'black'])
    


In [15]:
import numpy as np
import scipy.stats as st
xx= np.linspace(0.2,10,1001)
pl.figure()
θ= 2
for ν in range(1,10):
    a= ν/2
    yy= st.gamma(a= a , scale= θ).pdf(xx)
    pl.plot(xx,yy, label=f'a= {a}, θ= {θ}')
pl.title('Γ(a, θ).pdf(x)')
pl.xlabel('x')
pl.legend()
pl.figure()
for ν in range(1,10):
    yy= st.chi2(df= ν).pdf(xx)
    pl.plot(xx,yy, label=f'ν= {ν}')
pl.title('$χ^2(ν).pdf(x)$')
pl.xlabel('x')
pl.legend()


In [16]:
# Data Visualization
# Histogram
sampSize= 100
t= np.arange(sampSize)
# 你可以變換不同的機率分布來試試看
X= st.uniform(loc= 30, scale= 10).rvs(size= sampSize)
#X= st.norm(loc= 50, scale= 5).rvs(size= sampSize)
#X= st.gamma(a= 50, scale= 1).rvs(size= sampSize)
#X= st.randint(low= 30, high= 70).rvs(size= sampSize)
#X= st.binom(n= 100, p= .5).rvs(size= sampSize)
#X= st.poisson(mu= 30).rvs(size= sampSize)
#開始作圖，視覺化
fg, ax= pl.subplots(1,3)
# 隨機變數隨著時間軸 t 展開
ax[0].scatter(t,X)
ax[0].set_xlabel('t')
ax[0].set_ylabel('X')
ax[0].set_title('random variable, X(t)')
# 基本的 histogram
ax[1].hist(X, bins= 10, orientation= 'horizontal')
ax[1].set_xlabel('f(x)')
ax[1].set_ylabel('x')
ax[1].set_title('Histogram, f(x)')
# Linear regression
lr= st.linregress(t, X)
lr
# visualize the regression line
m= lr.slope
b= lr.intercept
x0= X.min()
x1= X.max()
t0= t[0]
t1= t[-1]
y0= m*t0+b
y1= m*t1+b
ax[0].plot([t0,t1],[y0,y1],'r')
# statistical description
des= st.describe(X)
des
## qq-plot
ax[2]= st.probplot(X, plot= pl)


In [17]:
# 淺嚐 pandas
# 運用 yfinance 撈股票價格歷史資料
import pandas as pd
import yfinance as yf
# 選3支股票，世界前 3大。
tks= yf.Tickers(['MSFT', 'AAPL', 'Googl'])
tks
# 撈1年的資料
tkPrice= tks.history(period='1y')
# 簡單作圖 X= X(t)
tkPrice.Close.plot()
tkPrice.Close.plot(logy= True)
# Histogram
tkPrice.Close.hist(orientation= 'horizontal')

#statistical description
tkPrice.Close.describe()


[*********************100%***********************]  3 of 3 completed


AAPL        GOOGL        MSFT
count  252.000000   252.000000  252.000000
mean   134.194284  2315.246230  257.836726
std     10.894635   393.542309   33.397220
min    113.152443  1720.219971  208.744629
25%    125.390247  2024.024994  231.380356
50%    132.788788  2308.439941  251.318069
75%    145.171154  2714.965027  286.873299
max    156.461655  2980.620117  336.989990

In [18]:
#AAPL:  Shares Outstanding  16.41B
#MSFT:  Shares Outstanding  7.51B
#GOOGL&GOOG: Implied Shares Outstanding 663.76M
# 公司總市值，$TrillionUSD
X0= tkPrice.Close.AAPL.apply(lambda x:  x*16.41/1e3) 
X1= tkPrice.Close.MSFT.apply(lambda x:  x*7.51/1e3)
X2= tkPrice.Close.GOOGL.apply(lambda x: x*.66376/1e3)
X= pd.DataFrame([X0,X1,X2])
X= X.T
X.plot(ylabel='$TrillionUSD', 
       #logy= True, 
       title='Market Capital (in $TrillionUSD)')


<AxesSubplot:title={'center':'Market Capital (in $TrillionUSD)'}, xlabel='Date', ylabel='$TrillionUSD'>