In [1]:
import sympy as sm


In [15]:
A= [[1,2],[3,4]]
A= sm.Matrix(A)

In [16]:
A

Matrix([
[1, 2],
[3, 4]])

In [17]:
A**-1 == A.inv()

True

In [18]:
A.row(0)

Matrix([[1, 2]])

In [19]:
A.col(0)

Matrix([
[1],
[3]])

In [23]:
A**3

Matrix([
[37,  54],
[81, 118]])

In [24]:
A*A*A

Matrix([
[37,  54],
[81, 118]])

In [33]:
(A.T*A)

Matrix([
[10, 14],
[14, 20]])

In [34]:
A.det()

-2

In [35]:
A.columnspace()

[Matrix([
 [1],
 [3]]),
 Matrix([
 [2],
 [4]])]

In [38]:
A.eigenvects()

[(5/2 - sqrt(33)/2,
  1,
  [Matrix([
   [-sqrt(33)/6 - 1/2],
   [                1]])]),
 (5/2 + sqrt(33)/2,
  1,
  [Matrix([
   [-1/2 + sqrt(33)/6],
   [                1]])])]

In [40]:
P,D= A.diagonalize()

In [41]:
P

Matrix([
[-sqrt(33)/6 - 1/2, -1/2 + sqrt(33)/6],
[                1,                 1]])

In [42]:
D

Matrix([
[5/2 - sqrt(33)/2,                0],
[               0, 5/2 + sqrt(33)/2]])

In [53]:
q= P*D*P.inv()
q

Matrix([
[(5/2 - sqrt(33)/2)*(-sqrt(33) - 3)*(-sqrt(33)/6 - 1/2)/(sqrt(33) + 11) + sqrt(33)*(-1/2 + sqrt(33)/6)*(5/2 + sqrt(33)/2)/11, 2*(5/2 - sqrt(33)/2)*(-sqrt(33)/6 - 1/2)/(sqrt(33)/2 + 11/2) + (-1/2 + sqrt(33)/6)*(5/2 + sqrt(33)/2)*(sqrt(33)/22 + 1/2)],
[                                        (5/2 - sqrt(33)/2)*(-sqrt(33) - 3)/(sqrt(33) + 11) + sqrt(33)*(5/2 + sqrt(33)/2)/11,                                         2*(5/2 - sqrt(33)/2)/(sqrt(33)/2 + 11/2) + (5/2 + sqrt(33)/2)*(sqrt(33)/22 + 1/2)]])

In [54]:
q

Matrix([
[(5/2 - sqrt(33)/2)*(-sqrt(33) - 3)*(-sqrt(33)/6 - 1/2)/(sqrt(33) + 11) + sqrt(33)*(-1/2 + sqrt(33)/6)*(5/2 + sqrt(33)/2)/11, 2*(5/2 - sqrt(33)/2)*(-sqrt(33)/6 - 1/2)/(sqrt(33)/2 + 11/2) + (-1/2 + sqrt(33)/6)*(5/2 + sqrt(33)/2)*(sqrt(33)/22 + 1/2)],
[                                        (5/2 - sqrt(33)/2)*(-sqrt(33) - 3)/(sqrt(33) + 11) + sqrt(33)*(5/2 + sqrt(33)/2)/11,                                         2*(5/2 - sqrt(33)/2)/(sqrt(33)/2 + 11/2) + (5/2 + sqrt(33)/2)*(sqrt(33)/22 + 1/2)]])

In [61]:
q.evalf()

Matrix([
[1.0, 2.0],
[3.0, 4.0]])

In [62]:
q

Matrix([
[(5/2 - sqrt(33)/2)*(-sqrt(33) - 3)*(-sqrt(33)/6 - 1/2)/(sqrt(33) + 11) + sqrt(33)*(-1/2 + sqrt(33)/6)*(5/2 + sqrt(33)/2)/11, 2*(5/2 - sqrt(33)/2)*(-sqrt(33)/6 - 1/2)/(sqrt(33)/2 + 11/2) + (-1/2 + sqrt(33)/6)*(5/2 + sqrt(33)/2)*(sqrt(33)/22 + 1/2)],
[                                        (5/2 - sqrt(33)/2)*(-sqrt(33) - 3)/(sqrt(33) + 11) + sqrt(33)*(5/2 + sqrt(33)/2)/11,                                         2*(5/2 - sqrt(33)/2)/(sqrt(33)/2 + 11/2) + (5/2 + sqrt(33)/2)*(sqrt(33)/22 + 1/2)]])

In [63]:
P

Matrix([
[-sqrt(33)/6 - 1/2, -1/2 + sqrt(33)/6],
[                1,                 1]])

In [64]:
D

Matrix([
[5/2 - sqrt(33)/2,                0],
[               0, 5/2 + sqrt(33)/2]])

In [65]:
P.inv()

Matrix([
[(-sqrt(33) - 3)/(sqrt(33) + 11), 2/(sqrt(33)/2 + 11/2)],
[                    sqrt(33)/11,     sqrt(33)/22 + 1/2]])

In [67]:
P.evalf()

Matrix([
[-1.45742710775634, 0.457427107756338],
[              1.0,               1.0]])

In [68]:
A

Matrix([
[1, 2],
[3, 4]])

In [72]:
a,b,c,d= sm.symbols('a,b,c,d')
A= [[a,b], [c,d]]
A= sm.Matrix(A)
A

Matrix([
[a, b],
[c, d]])

In [73]:
A.inv()

Matrix([
[ d/(a*d - b*c), -b/(a*d - b*c)],
[-c/(a*d - b*c),  a/(a*d - b*c)]])

In [74]:
A.det()

a*d - b*c

In [75]:
A.eigenvals()

{a/2 + d/2 - sqrt(a**2 - 2*a*d + 4*b*c + d**2)/2: 1,
 a/2 + d/2 + sqrt(a**2 - 2*a*d + 4*b*c + d**2)/2: 1}

In [76]:
A.eigenvects()

[(a/2 + d/2 - sqrt(a**2 - 2*a*d + 4*b*c + d**2)/2,
  1,
  [Matrix([
   [-d/c + (a/2 + d/2 - sqrt(a**2 - 2*a*d + 4*b*c + d**2)/2)/c],
   [                                                         1]])]),
 (a/2 + d/2 + sqrt(a**2 - 2*a*d + 4*b*c + d**2)/2,
  1,
  [Matrix([
   [-d/c + (a/2 + d/2 + sqrt(a**2 - 2*a*d + 4*b*c + d**2)/2)/c],
   [                                                         1]])])]

In [80]:
P,D= A.diagonalize()
display(P)
display(D)

Matrix([
[(a - d - sqrt(a**2 - 2*a*d + 4*b*c + d**2))/(2*c), (a - d + sqrt(a**2 - 2*a*d + 4*b*c + d**2))/(2*c)],
[                                                1,                                                 1]])

Matrix([
[a/2 + d/2 - sqrt(a**2 - 2*a*d + 4*b*c + d**2)/2,                                               0],
[                                              0, a/2 + d/2 + sqrt(a**2 - 2*a*d + 4*b*c + d**2)/2]])

In [123]:
a= sm.symbols('a:2:2')
a= np.array(a).reshape(2,2)
A= sm.Matrix(a)
A

Matrix([
[a00, a01],
[a10, a11]])

In [124]:
A.transpose()

Matrix([
[a00, a10],
[a01, a11]])

In [125]:
A.det()

a00*a11 - a01*a10

In [126]:
A.inv()

Matrix([
[ a11/(a00*a11 - a01*a10), -a01/(a00*a11 - a01*a10)],
[-a10/(a00*a11 - a01*a10),  a00/(a00*a11 - a01*a10)]])

In [127]:
A.det()*A.inv()

Matrix([
[ a11, -a01],
[-a10,  a00]])

In [128]:
A*A.transpose()

Matrix([
[  a00**2 + a01**2, a00*a10 + a01*a11],
[a00*a10 + a01*a11,   a10**2 + a11**2]])

In [130]:
A.eigenvals()

{a00/2 + a11/2 - sqrt(a00**2 - 2*a00*a11 + 4*a01*a10 + a11**2)/2: 1,
 a00/2 + a11/2 + sqrt(a00**2 - 2*a00*a11 + 4*a01*a10 + a11**2)/2: 1}

In [131]:
A.eigenvects()

[(a00/2 + a11/2 - sqrt(a00**2 - 2*a00*a11 + 4*a01*a10 + a11**2)/2,
  1,
  [Matrix([
   [-a11/a10 + (a00/2 + a11/2 - sqrt(a00**2 - 2*a00*a11 + 4*a01*a10 + a11**2)/2)/a10],
   [                                                                               1]])]),
 (a00/2 + a11/2 + sqrt(a00**2 - 2*a00*a11 + 4*a01*a10 + a11**2)/2,
  1,
  [Matrix([
   [-a11/a10 + (a00/2 + a11/2 + sqrt(a00**2 - 2*a00*a11 + 4*a01*a10 + a11**2)/2)/a10],
   [                                                                               1]])])]

In [134]:
P,D= A.diagonalize()

In [135]:
P

Matrix([
[(a00 - a11 - sqrt(a00**2 - 2*a00*a11 + 4*a01*a10 + a11**2))/(2*a10), (a00 - a11 + sqrt(a00**2 - 2*a00*a11 + 4*a01*a10 + a11**2))/(2*a10)],
[                                                                  1,                                                                   1]])

In [136]:
D

Matrix([
[a00/2 + a11/2 - sqrt(a00**2 - 2*a00*a11 + 4*a01*a10 + a11**2)/2,                                                               0],
[                                                              0, a00/2 + a11/2 + sqrt(a00**2 - 2*a00*a11 + 4*a01*a10 + a11**2)/2]])

In [137]:
P.inv()

Matrix([
[-a10/sqrt(a00**2 - 2*a00*a11 + 4*a01*a10 + a11**2),  (a00 - a11 + sqrt(a00**2 - 2*a00*a11 + 4*a01*a10 + a11**2))/(2*sqrt(a00**2 - 2*a00*a11 + 4*a01*a10 + a11**2))],
[ a10/sqrt(a00**2 - 2*a00*a11 + 4*a01*a10 + a11**2), (-a00 + a11 + sqrt(a00**2 - 2*a00*a11 + 4*a01*a10 + a11**2))/(2*sqrt(a00**2 - 2*a00*a11 + 4*a01*a10 + a11**2))]])

In [141]:
P*D*P.inv()

Matrix([
[-(a00/2 + a11/2 - sqrt(a00**2 - 2*a00*a11 + 4*a01*a10 + a11**2)/2)*(a00 - a11 - sqrt(a00**2 - 2*a00*a11 + 4*a01*a10 + a11**2))/(2*sqrt(a00**2 - 2*a00*a11 + 4*a01*a10 + a11**2)) + (a00/2 + a11/2 + sqrt(a00**2 - 2*a00*a11 + 4*a01*a10 + a11**2)/2)*(a00 - a11 + sqrt(a00**2 - 2*a00*a11 + 4*a01*a10 + a11**2))/(2*sqrt(a00**2 - 2*a00*a11 + 4*a01*a10 + a11**2)), (-a00 + a11 + sqrt(a00**2 - 2*a00*a11 + 4*a01*a10 + a11**2))*(a00/2 + a11/2 + sqrt(a00**2 - 2*a00*a11 + 4*a01*a10 + a11**2)/2)*(a00 - a11 + sqrt(a00**2 - 2*a00*a11 + 4*a01*a10 + a11**2))/(4*a10*sqrt(a00**2 - 2*a00*a11 + 4*a01*a10 + a11**2)) + (a00/2 + a11/2 - sqrt(a00**2 - 2*a00*a11 + 4*a01*a10 + a11**2)/2)*(a00 - a11 - sqrt(a00**2 - 2*a00*a11 + 4*a01*a10 + a11**2))*(a00 - a11 + sqrt(a00**2 - 2*a00*a11 + 4*a01*a10 + a11**2))/(4*a10*sqrt(a00**2 - 2*a00*a11 + 4*a01*a10 + a11**2))],
[                                                                                                                        -a10*(a00/2 + a11/2 - sqrt(a

In [144]:
P,D= (A*A.T).diagonalize()

In [145]:
P


Matrix([
[(a00**2 + a01**2 - a10**2 - a11**2 - sqrt((a00**2 - 2*a00*a11 + a01**2 + 2*a01*a10 + a10**2 + a11**2)*(a00**2 + 2*a00*a11 + a01**2 - 2*a01*a10 + a10**2 + a11**2)))/(2*(a00*a10 + a01*a11)), (a00**2 + a01**2 - a10**2 - a11**2 + sqrt((a00**2 - 2*a00*a11 + a01**2 + 2*a01*a10 + a10**2 + a11**2)*(a00**2 + 2*a00*a11 + a01**2 - 2*a01*a10 + a10**2 + a11**2)))/(2*(a00*a10 + a01*a11))],
[                                                                                                                                                                                          1,                                                                                                                                                                                           1]])

In [146]:
D

Matrix([
[a00**2/2 + a01**2/2 + a10**2/2 + a11**2/2 - sqrt((a00**2 - 2*a00*a11 + a01**2 + 2*a01*a10 + a10**2 + a11**2)*(a00**2 + 2*a00*a11 + a01**2 - 2*a01*a10 + a10**2 + a11**2))/2,                                                                                                                                                                           0],
[                                                                                                                                                                          0, a00**2/2 + a01**2/2 + a10**2/2 + a11**2/2 + sqrt((a00**2 - 2*a00*a11 + a01**2 + 2*a01*a10 + a10**2 + a11**2)*(a00**2 + 2*a00*a11 + a01**2 - 2*a01*a10 + a10**2 + a11**2))/2]])

In [147]:
P.inv()

Matrix([
[(-a00*a10 - a01*a11)/sqrt(a00**4 + 2*a00**2*a01**2 + 2*a00**2*a10**2 - 2*a00**2*a11**2 + 8*a00*a01*a10*a11 + a01**4 - 2*a01**2*a10**2 + 2*a01**2*a11**2 + a10**4 + 2*a10**2*a11**2 + a11**4),  (a00**2 + a01**2 - a10**2 - a11**2 + sqrt(a00**4 + 2*a00**2*a01**2 + 2*a00**2*a10**2 - 2*a00**2*a11**2 + 8*a00*a01*a10*a11 + a01**4 - 2*a01**2*a10**2 + 2*a01**2*a11**2 + a10**4 + 2*a10**2*a11**2 + a11**4))/(2*sqrt(a00**4 + 2*a00**2*a01**2 + 2*a00**2*a10**2 - 2*a00**2*a11**2 + 8*a00*a01*a10*a11 + a01**4 - 2*a01**2*a10**2 + 2*a01**2*a11**2 + a10**4 + 2*a10**2*a11**2 + a11**4))],
[ (a00*a10 + a01*a11)/sqrt(a00**4 + 2*a00**2*a01**2 + 2*a00**2*a10**2 - 2*a00**2*a11**2 + 8*a00*a01*a10*a11 + a01**4 - 2*a01**2*a10**2 + 2*a01**2*a11**2 + a10**4 + 2*a10**2*a11**2 + a11**4), (-a00**2 - a01**2 + a10**2 + a11**2 + sqrt(a00**4 + 2*a00**2*a01**2 + 2*a00**2*a10**2 - 2*a00**2*a11**2 + 8*a00*a01*a10*a11 + a01**4 - 2*a01**2*a10**2 + 2*a01**2*a11**2 + a10**4 + 2*a10**2*a11**2 + a11**4))/(2*sqrt(a00**4 + 2*a0

In [148]:
P*D*P.inv()

Matrix([
[(-a00*a10 - a01*a11)*(a00**2/2 + a01**2/2 + a10**2/2 + a11**2/2 - sqrt((a00**2 - 2*a00*a11 + a01**2 + 2*a01*a10 + a10**2 + a11**2)*(a00**2 + 2*a00*a11 + a01**2 - 2*a01*a10 + a10**2 + a11**2))/2)*(a00**2 + a01**2 - a10**2 - a11**2 - sqrt((a00**2 - 2*a00*a11 + a01**2 + 2*a01*a10 + a10**2 + a11**2)*(a00**2 + 2*a00*a11 + a01**2 - 2*a01*a10 + a10**2 + a11**2)))/(2*(a00*a10 + a01*a11)*sqrt(a00**4 + 2*a00**2*a01**2 + 2*a00**2*a10**2 - 2*a00**2*a11**2 + 8*a00*a01*a10*a11 + a01**4 - 2*a01**2*a10**2 + 2*a01**2*a11**2 + a10**4 + 2*a10**2*a11**2 + a11**4)) + (a00**2/2 + a01**2/2 + a10**2/2 + a11**2/2 + sqrt((a00**2 - 2*a00*a11 + a01**2 + 2*a01*a10 + a10**2 + a11**2)*(a00**2 + 2*a00*a11 + a01**2 - 2*a01*a10 + a10**2 + a11**2))/2)*(a00**2 + a01**2 - a10**2 - a11**2 + sqrt((a00**2 - 2*a00*a11 + a01**2 + 2*a01*a10 + a10**2 + a11**2)*(a00**2 + 2*a00*a11 + a01**2 - 2*a01*a10 + a10**2 + a11**2)))/(2*sqrt(a00**4 + 2*a00**2*a01**2 + 2*a00**2*a10**2 - 2*a00**2*a11**2 + 8*a00*a01*a10*a11 + a01**4 -

In [155]:
A= [[4,1],[1,4]]
A= np.array(A)
A

array([[4, 1],
       [1, 4]])

In [156]:
np.linalg.eig(A)

(array([5., 3.]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [157]:
A= sm.Matrix(A)
A

Matrix([
[4, 1],
[1, 4]])

In [158]:
A.diagonalize()

(Matrix([
 [-1, 1],
 [ 1, 1]]),
 Matrix([
 [3, 0],
 [0, 5]]))

In [160]:
sm.singularities?

Signature: sm.singularities(expression, symbol, domain=None)
Docstring:
Find singularities of a given function.

Parameters

expression : Expr
    The target function in which singularities need to be found.
symbol : Symbol
    The symbol over the values of which the singularity in
    expression in being searched for.

Returns

Set
    A set of values for ``symbol`` for which ``expression`` has a
    singularity. An ``EmptySet`` is returned if ``expression`` has no
    singularities for any given value of ``Symbol``.

Raises

NotImplementedError
    Methods for determining the singularities of this function have
    not been developed.

Notes
=====

This function does not find non-isolated singularities
nor does it find branch points of the expression.

Currently supported functions are:
    - univariate continuous (real or complex) functions

References

.. [1] https://en.wikipedia.org/wiki/Mathematical_singularity

Examples

>>> from sympy.calculus.singularities import singularities