In [102]:
# f(x)= x^4+ 4 x^3− 79 x^2− 226 x + 720
# x^∗=argmin_x  f(x)= ??

In [103]:
import numpy as np
import matplotlib.pyplot as pl

def f(x):
    y= x**4+ 4* x**3- 79 *x**2- 226 *x + 720
    return y
x= np.linspace(-10,10,1001) #100001)
y= f(x)
y

array([1080.        , 1051.24011216, 1022.79929856, ..., 4425.26278656,
       4492.37604816, 4560.        ])

In [104]:
pl.plot(x,y)

In [105]:
# [sol.01]
k_star= np.argmin(y)
k_star, x[k_star], y[k_star]

(784, 5.68, -1338.5454182400003)

In [106]:
# [sol.02]
import sympy as sm
x= sm.symbols('x')
df_dx= f(x).diff(x)
f(x), df_dx

(x**4 + 4*x**3 - 79*x**2 - 226*x + 720, 4*x**3 + 12*x**2 - 158*x - 226)

In [107]:
sol= sm.solve(df_dx, x)
sol

[-1 + (-1/2 - sqrt(3)*I/2)*(15/2 + 55*sqrt(1194)*I/36)**(1/3) + 85/(6*(-1/2 - sqrt(3)*I/2)*(15/2 + 55*sqrt(1194)*I/36)**(1/3)),
 -1 + 85/(6*(-1/2 + sqrt(3)*I/2)*(15/2 + 55*sqrt(1194)*I/36)**(1/3)) + (-1/2 + sqrt(3)*I/2)*(15/2 + 55*sqrt(1194)*I/36)**(1/3),
 -1 + 85/(6*(15/2 + 55*sqrt(1194)*I/36)**(1/3)) + (15/2 + 55*sqrt(1194)*I/36)**(1/3)]

In [108]:
# 可以找出 3個 微分(斜率) 為 0 之處
# 解出來可能含虛數(很小)，若很小很小，當作誤差要把它戶略掉
q= [s.evalf().as_real_imag()[0] for s in sol]
q

[-1.35398485103579, -7.33499813374491, 5.68898298478070]

In [109]:
# local min vs global min，要再檢查這個... 
qq= [f(s).evalf() for s in q]
qq

[874.603844119190, -556.543641549918, -1338.56020256927]

In [110]:
# 最後撈出其對應的 local min ，作為 global min
x_star= q[np.argmin(qq)]
x_star

5.68898298478070

In [111]:
from scipy.optimize import line_search


In [112]:
# perform a line search on a convex objective function that does not converge
from numpy import arange
from scipy.optimize import line_search
from matplotlib import pyplot
 
# objective function
def objective(x):
	#return (-5.0 + x)**2.0
    y= f(x)
    return y

 
# gradient for the objective function
def gradient(x):
	#return 2.0 * (-5.0 + x)
    s= sm.symbols('s')
    df_ds= f(s).diff(s)
    y= sm.lambdify(s, df_ds)(x)
    return y

 
# define the starting point
point = 0 #-5.0
# define the direction to move
direction = 1 #-3.0
# print the initial conditions
print('start=%.1f, direction=%.1f' % (point, direction))
# perform the line search
result = line_search(
    objective, 
    gradient, 
    point, 
    direction)
# summarize the result
#print('Alpha: %s' % result[0])
result

start=0.0, direction=1.0


(5.273291925465839, 6, 4, -1308.7514049259132, 720.0, -138.9382981879245)

In [113]:
f(x).diff(x)

4*x**3 + 12*x**2 - 158*x - 226

In [114]:
gradient(np.array([1,2,3]))

array([-368, -462, -484])

In [115]:
objective(np.array([1,2,3]))

array([ 420,    0, -480])

In [116]:
# Wiki example

X= [(1,6), 
    (2,5), 
    (3,7), 
    (4,10)]

def y_pred(x, β1, β2):
    y= β1 + β2*x
    return y

x, β1, β2= sm.symbols('x, β1, β2')
y_pred(x, β1, β2)

x*β2 + β1

In [117]:
def r(x, y, y_pred, β1, β2):
    r= y-y_pred(x,β1, β2)
    return r
X= np.array(X)
x= X[:,0]
y= X[:,1]
rr= r(x,y,y_pred, β1, β2)
rr

array([-β1 - β2 + 6, -β1 - 2*β2 + 5, -β1 - 3*β2 + 7, -β1 - 4*β2 + 10],
      dtype=object)

In [118]:
S= sum([rrr**2 for rrr in rr])
S

(-β1 - 4*β2 + 10)**2 + (-β1 - 3*β2 + 7)**2 + (-β1 - 2*β2 + 5)**2 + (-β1 - β2 + 6)**2

In [119]:
S.diff(β1)

8*β1 + 20*β2 - 56

In [120]:
S.diff(β2)

20*β1 + 60*β2 - 154

In [121]:
sol= sm.solve([S.diff(β1), S.diff(β2)], [β1, β2])
sol

{β1: 7/2, β2: 7/5}

In [122]:
sol.get(β1).evalf()

3.50000000000000

In [123]:
sol.get(β2).evalf()

1.40000000000000

In [124]:
# Wiki example
X= [(1,6), 
    (2,5), 
    (3,7), 
    (4,10)]

# 改變 資料點的產生方式
#'''
N= 100
X= np.random.normal(1, 10, size=(N,2))
X[:,1]= 1*X[:,0] +2 + np.random.normal(0, 10, size=(N,))
#'''

def y_pred(x, β1, β2):
    y= β1 + β2*x
    return y
x, β1, β2= sm.symbols('x, β1, β2')

y_pred(x, β1, β2)

x*β2 + β1

In [128]:
def r(x, y, y_pred, β1, β2):
    r= y-y_pred(x,β1, β2)
    return r

X= np.array(X)
xx= X[:,0]
yy= X[:,1]
rr= r(xx,yy,y_pred, β1, β2)
S= sum([rrr**2 for rrr in rr])
sol= sm.solve([S.diff(β1), 
               S.diff(β2)], 
               [β1, β2])

β1f, β2f= sol.get(β1).evalf(), sol.get(β2).evalf()

#pl.scatter(xx,yy)
#pl.plot(xx,y_pred(xx, β1f, β2f), 'blue')

β1f, β2f, S.subs({β1:β1f, β2:β2f})

(1.87239768659570, 0.815161986316674, 6495.56938016314)

In [129]:
pl.scatter(xx,yy)
pl.plot(xx,y_pred(xx, 2, 3), 'blue')
S.subs({β1:2, β2:3})


TypeError: loop of ufunc does not support argument 0 of type NoneType which has no callable sqrt method

In [ ]:
pl.scatter(x,y)
pl.plot(x,y_pred(x, -2, -3), 'blue')
S.subs({β1:-2, β2:-3})

In [ ]:
# Wiki example

# 延伸成 polynomial, e.g., degree=3

# 改變 資料點的產生方式
#'''
N= 100
X= np.random.normal(1, 10, size=(N,2))
X[:,1]= .01*X[:,0]**3 +2 + np.random.normal(0, 10, size=(N,))
#'''

def y_pred(x, β0, β1, β2, β3):
    y= β0 + β1*x +β2*x**2 +β3*x**3
    return y
x, β0, β1, β2, β3= sm.symbols('x, β0, β1, β2, β3')
y_pred(x, β0, β1, β2, β3)
def r(x, y, y_pred, β0, β1, β2, β3):
    r= y-y_pred(x,β0, β1, β2,β3)
    return r

X= np.array(X)
x= X[:,0]
y= X[:,1]

rr= r(x,y,y_pred, β0, β1, β2 ,β3)
S= sum([rrr**2 for rrr in rr])
sol= sm.solve([S.diff(β0), 
               S.diff(β1),
               S.diff(β2),
               S.diff(β3)], 
               [β0, β1, β2, β3])

β0f, β1f, β2f, β3f= [
    sol.get(β0).evalf(), 
    sol.get(β1).evalf(),
    sol.get(β2).evalf(), 
    sol.get(β3).evalf()
]

pl.scatter(x,y)
pl.scatter(x,y_pred(x, β0f,β1f, β2f, β3f))


β0f, β1f, β2f, β3f, S.subs({β0:β0f,β1:β1f, β2:β2f,  β3:β3f})

In [ ]:
pl.scatter(x, y_pred(x, β0f,β1f, β2f, β3f))

β0f, β1f, β2f, β3f,

In [ ]:
x.shape, y.shape

In [ ]:
from sklearn import linear_model
reg= linear_model.LinearRegression()

reg.fit(
    [[0], [1], [2]], 
    [1, 3, 8]
)

reg.intercept_, reg.coef_

In [ ]:
x= x.astype('float').reshape(-1,1)
y= y.astype('float')
pl.scatter(x,y)

In [ ]:
reg= linear_model.LinearRegression()
reg.fit(x, y)
reg.intercept_, reg.coef_

In [131]:
# HomeWorkCh04_02

import numpy as np
import matplotlib.pyplot as pl
def generateY(x, w):
    ϵ= np.random.normal(
        loc=   0.0, 
        scale= np.random.uniform(1,10), 
        size= x.shape[1])    
    x= np.concatenate(
            (np.ones((1,N)),
             x), 
            axis=0)
    y= w.T@x +ϵ
    return y
np.random.seed(0)
N=    100
low= -3.0
high= 4.0
b= -3  # y軸 截距
w= np.array([b, 3, -2]) #.reshape(-1,1)
x= np.random.uniform(low= low, 
                     high=high, 
                     size=(2,N))
y= generateY(x, w)
%matplotlib qt
ax= pl.axes(projection='3d')
ax.scatter3D(x[0,:],x[1,:],y, color='red')
ax.set_xlabel('$x_0$')
ax.set_ylabel('$x_1$')
ax.set_zlabel('$y$')


Text(0.5, 0, '$y$')

In [ ]:
x.shape, y.shape

In [134]:
# 要用 scikit-learn 的話， x 要轉置成 (100,2)
xT= x.T

# 然後，就一步到位！
reg= linear_model.LinearRegression()
reg.fit(xT, y)

# answer:
reg.intercept_, reg.coef_

(-3.41405079445415, array([ 2.70205492, -2.03634216]))

In [132]:
# 回到 Normal Equation
# 如何把 Φ 接好接滿是一個小小的學問， numpy 要夠熟！
Φ= np.concatenate(
    [np.ones((x.T.shape[0],1)), 
     x.T], axis=1)
Φ.shape

weights= np.linalg.inv(Φ.T @ Φ) @ Φ.T @ y
weights

array([-3.41405079,  2.70205492, -2.03634216])